/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "./s21_math.h" instead.
 */

#include <check.h>

#ifndef _S21_MATH_H
#define _S21_MATH_H

#define S21_EPSILON (1e-6)
#define S21_VERY_SMALL_EPSILON (1e-11)
#define S21_VERY_VERY_SMALL_EPSILON (1e-26)
#define S21_PI (3.14159265358979323846264338327950288)
#define S21_M_PI (3.14159265358979323846264338327950288)
#define S21_E (2.71828182845904523536028747135266250)
#define S21_INFINITY (1.0 / 0.0)
double S21_NAN();
int s21_isNan(double x);

long int s21_abs(int x);  // вычисляет модуль целого числа
long double s21_fabs(double x);  // вычисляет модуль с плавающей точкой

long double s21_signl(double x);  // возвращает знак
int s21_isInt(long double x);  //  возвращает является ли число целым

long double s21_ceil(double x);   // округление вверх
long double s21_floor(double x);  // округление вниз

double s21_max(double x, double y);  // возвращает максимум

long double s21_exp(double x);  // возвращает e, возведенное в степень x
long double s21_pow(double base, double exp);  // возводит число в степень
long double s21_powi(double base,
                     unsigned int exp);  // возводит число в целую степень
long double s21_sqrt(double x);  // вычисляет квадратный корень

long double s21_factorial(unsigned int x);  // факториал

long double s21_fmod(double x, double y);  // остаток от деления double
long double s21_fdiv(double x, double y);

long double s21_log(double x);  // вычисляет натуральный логарифм

long double s21_acos(double x);  // вычисляет арккосинус
long double s21_asin(double x);  // вычисляет арксинус
long double s21_atan(double x);  // вычисляет арктангенс

long double s21_sin(double x);  // вычисляет синус
long double s21_cos(double x);  // вычисляет косинус
long double s21_tan(double x);  // вычисляет тангенс

#endif  // _S21_MATH_H
#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include "s21_math.h"
#include <check.h>
#include <math.h>
#include <stdio.h>

#include "s21_math.h"

START_TEST(s21_acos_test)
{
for (double i = -1; i <= 1; i += 0.1) {
  ck_assert_double_eq_tol(acosl(i), s21_acos(i), S21_EPSILON * 10);
}
#include <check.h>
#include <math.h>
#include <stdio.h>

#include "s21_math.h"

}
END_TEST

START_TEST(s21_asin_test)
{
for (double i = -1; i <= 1; i += 0.1) {
  ck_assert_double_eq_tol(asinl(i), s21_asin(i), S21_EPSILON);
}
#include <check.h>
#include <math.h>
#include <stdio.h>

#include "s21_math.h"

}
END_TEST

START_TEST(s21_atan_test)
{
for (double i = 0; i <= 100; i += 0.1) {
  ck_assert_double_eq_tol(atanl(i), s21_atan(i), S21_EPSILON * 10);
}
#include <check.h>
#include <math.h>

#include "s21_math.h"

}
END_TEST

START_TEST(s21_ceil_test)
{
for (double i = -1000; i <= 10000; i += 0.1) {
  ck_assert_double_eq_tol(ceil(i), s21_ceil(i), S21_EPSILON);
}
#include <check.h>
#include <math.h>
#include <stdio.h>

#include "s21_math.h"

}
END_TEST

START_TEST(s21_cos_test)
{
for (double i = -100; i <= 100; i += 0.1) {
  ck_assert_double_eq_tol(cosl(i), s21_cos(i), S21_EPSILON);
}
#include <check.h>
#include <math.h>
#include <stdio.h>

#include "s21_math.h"

}
END_TEST

START_TEST(s21_exp_test)
{
for (double i = -100; i < -50; i += 0.5) {
  ck_assert_ldouble_eq_tol(s21_exp(i), expl(i), S21_EPSILON);
}
#include <check.h>
#include <math.h>
#include <stdio.h>

#include "s21_math.h"

}
END_TEST

START_TEST(s21_floor_test)
{
for (double i = -1000; i <= 10000; i += 0.1) {
  ck_assert_double_eq_tol(floor(i), s21_floor(i), S21_EPSILON);
}
#include <check.h>
#include <math.h>

#include "s21_math.h"

}
END_TEST

START_TEST(s21_fmod_test)
{

for (double i = 0; i <= 100000; i += S21_E) {
  ck_assert_double_eq_tol(fmod(i, 1), s21_fmod(i, 1), S21_EPSILON);
  ck_assert_double_eq_tol(fmod(-i, 1), s21_fmod(-i, 1), S21_EPSILON);
  ck_assert_double_eq_tol(fmod(i, S21_PI), s21_fmod(i, S21_PI), S21_EPSILON);
  ck_assert_double_eq_tol(fmod(-i, S21_PI), s21_fmod(-i, S21_PI), S21_EPSILON);
  ck_assert_double_eq_tol(fmod(i, -1), s21_fmod(i, -1), S21_EPSILON);
  ck_assert_double_eq_tol(fmod(-i, -1), s21_fmod(-i, -1), S21_EPSILON);
  ck_assert_double_eq_tol(fmod(i, -S21_PI), s21_fmod(i, -S21_PI), S21_EPSILON);
  ck_assert_double_eq_tol(fmod(-i, -S21_PI), s21_fmod(-i, -S21_PI),
                          S21_EPSILON);
}
#include <check.h>
#include <math.h>
#include <stdio.h>

#include "s21_math.h"

}
END_TEST

START_TEST(s21_log_test)
{

for (double i = 0.01; i <= 1000; i += 0.1) {
  long double s21_res = s21_log(i);
  long double res = log(i);
  printf("s21_res == %Lf\nres == %Lf\n\n", s21_res, res);

  ck_assert_double_eq_tol(res, s21_res, S21_EPSILON);
}
}
END_TEST

START_TEST(s21_log_test_zero)
{
ck_assert_double_eq(logl(0), s21_log(0));


#include <check.h>
#include <math.h>
#include <stdio.h>

#include "s21_math.h"

}
END_TEST

START_TEST(test_s21_pow)
{
for (double i = 5; i < 15; i++) {
  for (double j = 0; j <= 30; j += 0.1) {
    long double s21_res = s21_pow(i, j);
    long double res = pow(i, j);
    long double diff = res - s21_res;
    //ck_assert_ldouble_eq_tol(s21_res, res, 100);
  }
}
#include <check.h>
#include <math.h>
#include <stdio.h>

#include "s21_math.h"

}
END_TEST

START_TEST(test_s21_powi)
{
for (unsigned int i = 0; i < 10; i++) {
  for (double j = 0; j < 3; j += 0.01) {
    ck_assert_ldouble_eq_tol(s21_powi(j, i), powl(j, i), S21_EPSILON);
  }
}
#include <check.h>
#include <math.h>
#include <stdio.h>

#include "s21_math.h"

}
END_TEST

START_TEST(s21_sin_test)
{
for (double i = -100; i <= 100; i += 0.1) {
  ck_assert_double_eq_tol(sinl(i), s21_sin(i), S21_EPSILON);
}
#include <check.h>
#include <math.h>
#include <stdio.h>

#include "s21_math.h"

}
END_TEST

START_TEST(s21_tan_test)
{
for (double i = -100; i <= 100; i += 0.1) {
  ck_assert_double_eq_tol(tanl(i), s21_tan(i), S21_EPSILON);
}
#include <stdlib.h>
#include "s21_abs.c"

}
END_TEST

START_TEST(abs_test)
{
int x = -25;    
ck_assert_uint_eq(s21_abs(x), abs(x));
x = 25;    
ck_assert_uint_eq(s21_abs(x), abs(x));
#include <stdlib.h>

#include "s21_fabs.c"

}
END_TEST

START_TEST(fabs_test)
{
int x = -25;
ck_assert_uint_eq(s21_fabs(x), fabs(x));
x = 25;
ck_assert_uint_eq(s21_fabs(x), fabs(x));
#include <stdlib.h>
#include "s21_sqrt.c"

}
END_TEST

START_TEST(sqrt_test)
{
for (int i = 0; i < 100; i++){
ck_assert_double_eq_tol(s21_sqrt(i), sqrt(i), S21_EPSILON);
}
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, s21_acos_test);
    tcase_add_test(tc1_1, s21_asin_test);
    tcase_add_test(tc1_1, s21_atan_test);
    tcase_add_test(tc1_1, s21_ceil_test);
    tcase_add_test(tc1_1, s21_cos_test);
    tcase_add_test(tc1_1, s21_exp_test);
    tcase_add_test(tc1_1, s21_floor_test);
    tcase_add_test(tc1_1, s21_fmod_test);
    tcase_add_test(tc1_1, s21_log_test);
    tcase_add_test(tc1_1, s21_log_test_zero);
    tcase_add_test(tc1_1, test_s21_pow);
    tcase_add_test(tc1_1, test_s21_powi);
    tcase_add_test(tc1_1, s21_sin_test);
    tcase_add_test(tc1_1, s21_tan_test);
    tcase_add_test(tc1_1, abs_test);
    tcase_add_test(tc1_1, fabs_test);
    tcase_add_test(tc1_1, sqrt_test);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
